### PR TITLE
`poetry` adaptation and use of `prompt_toolkit`

### PR DESCRIPTION
**Pull request by n3rada**
Transitioned the project to use poetry for dependency management and packaging, aligning with modern Python project standards.

Adding the [`prompt_toolkit`](https://github.com/prompt-toolkit/python-prompt-toolkit) command handler which is the go-to tool for fake console. It includes in-memory history and lot of other features.

### CODE REVIEW

**Comment by aniqfakhrul** [comment]
We will review this changes and get back to you. Also, great suggestion,didn't know prompt_toolkit is a thing before xD. Thanks!

**Comment by cmprmsd** [comment]
I think autocompletion is gone with this PR.

**Comment by aniqfakhrul** [comment]
Have you tried? Havent got a chance to test this yet.

**Comment by cmprmsd** [comment]
Yes I did. :+1: 
Can't say something about the other changes but this caught my eyes, because I just stumbled over your project and don't know all flags yet. Nice toolset! 
I was especially looking for group membership handling without having to use a Windows system. :rocket:

**Comment by n3rada** [comment]
Maybe you'll have to adjust the code in order to have your auto completion work well. I do not have time to make everything good around that point without whole code knowledge,  I particularly wanted to show you in a quick and not so dirty way how `prompt_toolkit` works!

**Comment by n3rada** [comment]
Up @aniqfakhrul?

**Comment by n3rada** [comment]
Yes, without any responses in 4 months, I wanted to clean up my repos

**Pull request closed without merging**
